# Generated by Django 3.2.4 on 2021-06-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=249, null=True)),
                ('authors', models.CharField(max_length=500, null=True)),
                ('published_date', models.CharField(max_length=100, null=True)),
                ('categories', models.CharField(max_length=500, null=True)),
                ('average_rating', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ratings_count', models.PositiveBigIntegerField(null=True)),
                ('thumbnail', models.CharField(max_length=300, null=True)),
            ],
            options={
                'unique_together': {('title', 'authors', 'published_date')},
            },
        ),
    ]
